[package]
name = "xbulk-meta"
version = "0.0.0"
edition = "2021"
publish = false
authors = [ "Alessandro De Franceschi <info@defralcoding.it>",]

[dev-dependencies]

[dependencies.xbulk]
path = ".."

[dependencies.elrond-wasm-debug]
version = "0.34.1"
