[package]
name = "xbulk-meta"
version = "2.0.0"
edition = "2021"
publish = false
authors = ["Alessandro De Franceschi <info@dbcodingsrl.com>"]

[dev-dependencies]
[dependencies.xbulk]
path = ".."

[dependencies.multiversx-sc-meta]
version = "0.41.0"
