[package]
name = "elrond-bulk-meta"
version = "0.0.0"
edition = "2021"
publish = false
authors = [ "Alessandro De Franceschi <info@defralcoding.it>",]

[dev-dependencies]

[dependencies.elrond-bulk]
path = ".."

[dependencies.elrond-wasm-debug]
version = "0.31.1"
